name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: install templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.1020
      - name: templ generate
        run: templ generate
      - name: build
        run: go build ./...
      - name: vet
        run: go vet ./...
      - name: test
        run: go test ./...
